# Generated by Django 4.2.2 on 2025-06-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0017_panels_display'),
        ('meeting_minutes', '0002_rename_date_meetingminutes_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='sc_ag',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='port.chapters_society_and_affinity_groups'),
            preserve_default=False,
        ),
    ]
