# Generated by Django 4.2.2 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minutes', '0003_meetingminutes_sc_ag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='ieee_attendee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='total_attendee',
            field=models.IntegerField(default=0),
        ),
    ]
