# Generated by Django 4.2.2 on 2025-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_administration', '0014_fct_data_access_create_budget_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc_ag_data_access',
            name='manage_email_access',
            field=models.BooleanField(default=False),
        ),
    ]
